### PR TITLE
Use ConfigMaps CreationDate for JKS CreateDate property

### LINKED ISSUE #142: truststore.jks in ConfigMaps updated on every pod restart
We have ConfigMaps with Certificates that we convert to JKS with the help of cert-utils-operator (`cert-utils-operator.redhat-cop.io/generate-java-truststore` annotation, currently using v1.3.9). We also have Stakater Reloader that restart our apps as truststores change.

We have discovered that when Cert-Utils-Operator restarts all our ConfigMaps are updated. And then Stakater Reloader kicks in and restarts apps. Even nothing has changed with certs.

This is probably due to the non-idempotent creation of the JKS which involves `time.Now()`:

https://github.com/redhat-cop/cert-utils-operator/blob/master/controllers/configmaptokeystore/configmap_to_keystore_controller.go#L136-L147

Probably this is a required field. :-|

### PR DESCRIPTION
**Pull request by vinzent**
This requires the keystore-go to be updated to v4 and this requires at least go 1.17. So i've updated to go 1.20 too.

I've added a new test case to check the equality of the JKS after two reconciles. The issues only started to exist, when then ca-bundle.crt contained many certs. So i've included the Mozilla CA list as testdata. Once I remove
`keystore.WithOrderedAliases()`, the test fails.

Fixes #142

### CODE REVIEW

**Comment by vinzent** [comment]
I will now build the image and test it on our internal cluster.

**Comment by vinzent** [comment]
@raffaelespazzoli I can confirm, that with this patch applied, the ConfigMap truststore.jks is no more updated on every restart of the cert-utils-operator pods.

**Comment by raffaelespazzoli** [comment]
can you rebase?

**Comment by vinzent** [comment]
> can you rebase?

done.

**Pull request merged**
